### ISSUE TITLE
Listened bugs (pre-release 4)

### ISSUE THREAD

**Issue by werasik2aa** [Filigrani/SkyCoop#1]
Filigrani — 23.05.2021
1. Rabbits are disabled.
2. Some spawned animals not registered to any spawn region, this makes spawn region create not correct amount of animals.
3. If player knocked down, other player can see message about reviving on zero XYZ, if both players locates in different scenes.
4. Player knocked body can work incorrect, if player died when other player was in different scene when this happened.
5. Equipping items may case to rare crash ### **_cause of out of date ModCompoent version_** (Will be fixed in Release version 4).

**Comment by Filigrani** [comment]
This very old message and this totally lose any actuality, also this been listed in official discord for many years, not know what was a point of making this message, howeever all listed things here has been fixed for many time ago
