### ISSUE TITLE
Joiners meat spoils more or less instantly.

### ISSUE THREAD

**Issue by Lussian-A** [Filigrani/SkyCoop#11]
This is for 6.1 Beta 1 Obviously. 

Just noticed after last nights sessions that my friend who joins me, has his meat spoiled almost instantly. 

After some more keen eyed session, we noticed that the host suffers no problems, but clients seems to generally have their items degrade 2-4 times faster than the host, sometimes instantly in the case of meat, as he remarked when I entered the building he was in while he was in his inventory and he saw his meat drop from 50'ish to ruined in the blink of an eye.

So definitely somethin goin on here. Cloths degraded faster as well. 

Animals seem to multiply now and then if we shoot at them and sometimes seem to soak up wayyy too many bullets, like 15 revolver bullets for one wolf at the worst :D 

Fascinating stuff. Anyways, keep up the good work.

**Comment by Filigrani** [comment]
Yes, we still trying to find why this happends, but looks like a when host change scene during loading time host does not sends time, and it makes client use his own time that different due of skiping time problems, and it makes it work wrong.
`I entered the building he was in while he was in his inventory and he saw his meat drop from 50'ish to ruined in the blink of an eye.` this your note will help a lot thank you, we will keep search how we can fix this.
