### ISSUE TITLE
Random game crash

### ISSUE THREAD

**Issue by RinWate** [Filigrani/SkyCoop#12]
The game sometimes just crashes. It may not fly out for a day, but the next day it takes off again.
It happens like this:
The game freezes several times in a row, then the application just closes

**Comment by RinWate** [comment]
![image](https://user-images.githubusercontent.com/42698624/137480821-e3b36b2f-ffdd-4eee-bec1-f65bd247ec0b.png)

**Comment by Filigrani** [comment]
It has been fixed in version 6.1 beta 2.
