### ISSUE TITLE
Loot containers and some transitioned to building/containers shows as empty even before being searched

### ISSUE THREAD

**Issue by poptart0969** [Filigrani/SkyCoop#17]
I first noticed this issue while in wintermute storymode while utilizing this mod and melonloader. The incident began while I was in the mine looking for detonator caps. I died in the mine and loaded to a previous save in the mine. Lootable items were no longer there to include and container and the elevator crank. I reloaded to a save before entering the mine with the same result. I found the same result after restarting the game, my PC. I thought I had found a work around as I had discovered that verifying the file integrity of TLD allowed the world loot to populate. Sadly, my temporary fix does not seem to impact the Blackrock substation and its contents but does fix the truck outside of the old substation.  Thanks

**Comment by Filigrani** [comment]
Fixed in now days builds of the mods. After release version 9.7 (if not count pre-releases) has been completly rewriten whole saving of the gears and containers, so this problem should not appear in current releases of the mod.
