### ISSUE TITLE
All the drops disappear after loading the save

### ISSUE THREAD

**Issue by Kycko** [Filigrani/SkyCoop#18]
Hello!
Today we decided to try _**8.0 pre-release**_, but I think this bug was in previous versions too (but I'm not sure).

I've loaded my save file and I saw on the ground all the items dropped in the previous game session. After that I've hosted my game and sent an invite to my friend (we play via Steam). When he was connecting to me all the items on the ground suddenly disappeared...
Interesting fact is that we decided to close our games and reconnect again, and the second one was successful 🤗: all the items was on it's places after connection.

**Comment by Kycko** [comment]
@ljans information about drops is saving to Unloads folder in the same time the game makes it's save. All the current data is stored in RAM or maybe in some temporary files. I think it's normal behaviour for this mod to exit from the game completely when you click on exit in the main menu after hosting.
Saying about Cedar firewood it's also normal, all your containers will be restored after connecting with your teammate.

**Comment by Lussian-A** [comment]
Yeah this happened to us also. All our dropped items have been wiped clean. That's ... kinda rough after a good 20 hour game :|
Nothing in the unload folder. 
Had a few crashes on exit. This is 7.7 as 8.0.4 had weird animal spawning, wolves kept spawning next to us constantly.

**Comment by Filigrani** [comment]
Fixed in now days builds of the mods. After release version 9.7 (if not count pre-releases) has been completly rewriten whole saving of the gears and containers, so this problem should not appear in current releases of the mod.

**Comment by ljans** [comment]
Thanks for your great work on this mod!
