### ISSUE TITLE
Fake Container

### ISSUE THREAD

**Issue by TheRadiance** [Filigrani/SkyCoop#19]
When my friend tries to open a container that has been searched (whether there are items in the container or not), the screen will show "please wait" and then get stuck forever.
“ [Sky_Co-op] Opening container, request fake container
 [Sky_Co-op] [DroppedGearsUnloader] Going to load container d7c374f2-2e65-4f71-b63a-97f61ec4219b
 [Sky_Co-op] [ContainersLoader] Saves found”

**Comment by Filigrani** [comment]
All similar problems has been fixed by completely rewritten system of storing and saving container data. So such problem should not appear in one days mod builds
