### ISSUE TITLE
Save game does not work after first save attempt

### ISSUE THREAD

**Issue by vicked** [Filigrani/SkyCoop#2]
Affected versions: V3, V4 Experimental

Test steps:
1) start game and enable host as 
2) other player joins the game (player-2)
3) player-2 goes to an indoor location to trigger save game
4) player-2 quits the game
5) player-2 joins the game again -> result: player-2 is in the indoor location of the last save game (as expected)
6) player-2 loots something
7) player-2 goes outside and then goes to an ANOTHER indoor location to trigger save game 
8) player-2 quits the game
9) player-2 joins the game again

Expected result: player-2 logged in at the ANOTHER indoor location
Actual result: player-2 logged in at the FIRST indoor location

**Comment by Filigrani** [comment]
Fixed in release 5 and above.
