### ISSUE TITLE
Co-op Custom Game Settings

### ISSUE THREAD

**Issue by saraminecraft** [Filigrani/SkyCoop#20]
When trying to start a game with custom settings, after selecting custom settings there is no setting page which comes up as in singleplayer. How do I set the custom settings for a multiplayer game? Such as turning player dialogue off.

**Comment by Filigrani** [comment]
Experimental ability to use custom experience mode was added, but still is not properly tested, you can use it on your own risk but we not promise that every option there is working for sure.
