### ISSUE TITLE
Parasites & Cabin Fever can't be cured

### ISSUE THREAD

**Issue by Lussian-A** [Filigrani/SkyCoop#21]
Hey, been testing out 9.5 a bit.

So far it seems item duplication doesn't work anymore? Aka if I loot a container it's empty for everyone else even if the item duplication option is checked. And if I leave anything behind in a searched container it vanishes.

and 2nd, any arrows shot at animals disappear.... this makes archery useless. 

Thanks.

**Comment by Lussian-A** [comment]
3rd note, spawn seems to be on hyperdrive. We had 10 wolves at the lake in mystery lake, killed all and shortly after there were 8 more. I think your experimental spawn might be a bit broke, unless you've upped the difficulty without telling us. :D

**Comment by Lussian-A** [comment]
Right, the arrows disappearing seems related to how the animal is told to "despawn" after being killed and is replaced with a corpse. Thus it removes any arrows currently in it. I believe this was a non-issue in 8.x But it's been a while so can't say for certain.

**Comment by Lussian-A** [comment]
4th Issue. So far Cabinfever and Intestinal Parasites do not get cured. 

Intestinal Parasites allow you to take the first treatment dose, but no matter how much time passes, you're not allowed to take the subsequent doses.

Cabinfever just keeps building up and once you get it, even if you sleep/workout doors for 24 hours, you get 3 messages, risk of cabinfever, healed cabinfever and then get a new stack of cabinfever >.>

Thanks, I'll be here all week tossing issues :D

**Comment by Lussian-A** [comment]
and another, Blackrock workshop won't open even after we got the code, it works if I turn it unto a singleplayer game and do it, but locks again the moment I make it a multiplayer game. 

I suspect the same will happen in Bleak Inlet with the cannery workshop

**Comment by Filigrani** [comment]
Thanks for your message. Currently on version of the mod 9.9b arrows inside animals is now finally synced. This known bug happend when animal changed controller player, so arrows destoryed every time animal changed target player or been killed. Now animals sync data store arrows that located inside animal, and that arrows drops around corpse when animal dies. So archery not useless anymore! However arrows restores condition when they dropped, so this an problem that I am still work to fix

**Comment by Filigrani** [comment]
About keypads based doors, I still need more invistigation but honestly I did not really got time to really pay attention of this one problem, I hope soon I will be able to.

**Comment by Filigrani** [comment]
Also about cabin fever and intestinal parasites this problem stays from very begining, because client does not know what day currently is, and whole timeline cycle of the game really broken right now, so it need  a lot of time to rework this too

**Comment by Lussian-A** [comment]
Well, at least the arrow thing makes archery useful again. 

Keypad we could only get around by using the a bit too hard to use noclip console commands. Not really a plausible solution due to inventory management. So here to hoping ya find a solution.

Cabin fever and intestinal parasites I guess we'll just cure with console commands for now.

Thanks and keep up the good job.

**Comment by Filigrani** [comment]
I am changed title of the issue, because previous one was kinda out of date, so now new users won't send dublicated reports and I am myself wont forget what has been listed in this report, I hope you not mind

**Comment by Lussian-A** [comment]
Not a problem.

**Comment by Filigrani** [comment]
Problem with keypad based doors is no more. It has been fixed in build 10.2, read changelog of this release if you interested how it been fixed. But shortly, yes it works as it expected now.

**Comment by Lussian-A** [comment]
Yeah, I was gonna give it a test. But it seems I can't run version 10.x as it seems to crash in the menu. So I made a different post with a log file attached.

**Comment by Filigrani** [comment]
Cabin fever now is disabled in multiplayer, Risk of Parasites now evolved to long food poison instead.
