### ISSUE TITLE
Furnace burning time desynchronization

### ISSUE THREAD

**Issue by DereksDimension** [Filigrani/SkyCoop#34]
**Mod Version:** v10.4
**Game Version:** v2.02
**Launcher:** Steam
**Additional mods installed:** No
**Perspective:** Both

### Description
Me and my friend were in the Camp Office and I lit the stove, burning time was 2 hours, then I started reading a book for one hour, after that burning time became 1 hour, but my friend still had 2 hours of oven burning time.

### How to reproduce
1. Being host.
2. On region 'Mistery Lake (Camp Office)'
3. Do  'fire up the stove, remember burning time for you and your friend, read the book or do something that takes time, then check burning time for both of you'
3. It works wrong.

### Expected behavior
I expected, that reading the book will not affect to burning time, or will affect for both of us, not only for me.

**Comment by Filigrani** [comment]
This not a bug, YOUR fire on YOUR local timeline, not on global timeline, to avoid abuse of sleeping, because else, you would be able to cook, and sleep without wasting of time. Everything works as intended.

**Comment by Filigrani** [comment]
There no plans to rewrite fire on global timeline, because it case to large balance problems that will require remake cooking and sleeping in real time to make it work properly. Also waiting HOURS in real time is not fun. So this logical game compromise we end up with.
