### ISSUE TITLE
This save file can't be use for multiplayer, because was created on old version of mod or without mod at all

### ISSUE THREAD

**Issue by VanchellaV** [Filigrani/SkyCoop#37]
**Mod Version:** v10.4.0
**Game Version:** v2.02 
**Launcher:** Steam   
**Additional mods installed:** No  
**Perspective:** Host

### Description
downloaded the mod and created the game on 10/25/22
10/26/22 I try to start the save and the game gives an error
game and mod after the creation of the world was not updated
Even in the logs it is written about the error of the melonloader, maybe this is somehow connected?

[MelonLoader_22-10-26_22-51-08.015.log](https://github.com/Filigrani/SkyCoop/files/9873347/MelonLoader_22-10-26_22-51-08.015.log)

![image_2022-10-26_22-42-16](https://user-images.githubusercontent.com/116760287/198124723-c02ab687-930e-4897-a08b-37ae5c4c0bfc.png)

**Comment by Filigrani** [comment]
Can you please give log from previous session, when save has been created?

**Comment by Filigrani** [comment]
Maybe you have two saves with same name?

**Comment by VanchellaV** [comment]
Before writing about the problem, I reinstalled melonloader and mod and the previous log was deleted (at that moment I did not think to write to you and thought that reinstallation would help)
I created a new world, now everything works fine, it does not give an error, although I did everything in the game in much the same way
Thank you for your reply and for making this mod.

**Comment by Filigrani** [comment]
Okay then, report once again if you get any problems. I will close this issue then
