### ISSUE TITLE
Bug discovered (release 5.5)

### ISSUE THREAD

**Issue by NicksQ69** [Filigrani/SkyCoop#5]
**Hi,** 
me and my friend thank you very much for setting up this mod which is just amazing!
And to thank you, we want to share with you the bugs and ideas we discovered after 9 hours of playing the "SkyCoop" mod version 5.5.

> To play multiplayer, we had to activate the "public host" and "steam peer to peer" options as well as disable the firewall for public networks to avoid any blocking using hamachi. Is it possible to obtain the port used to open the connection (udp / tcp?), because with the help of the ngrok software (ngrok.com), it is possible to easily open a port on your pc from the internet without manipulating your router. And thus to do without hamachi.

> Even if it is recommended by you, we tried the connect via ip button directly from the menu but without success. We had to use the steam invitation method.

> The gender of the characters are not maintained. Each time we start the session with my friend, we discover ourselves as men and then women the next day.

> Sometimes my friend sees things and objects that I don't, and vice versa. Similarly for animals, we were attacked by a group of wolves, some of which were seen by my friend and was ignored, and they attacked me.

> The objects that my friend puts down, I don't see them and vice versa.

> Duplication problems, we suppose that when one is in full animation (sleeping ...), if we send him an object from our inventory, it duplicates it (in some cases).

> When sharing a firearm, if the weapon is loaded, when sharing the ammunition is destroyed. 

> Likewise, when we make a fire, my friend does not see it and vice versa.

Otherwise, no crash reported!
I say it again, it's a very good job and thanks again!
I'm sorry if my sentences seem incorrect, or incomprehensible. If you don't understand, don't hesitate to ask me again.
Can't wait for the next updates!

**Comment by davi919** [comment]
Hi, 
I confirm all your bugs but I add one, if I host, I can kill all the animals but if another player shoots one, it becomes immortal, sometimes it "dies" but the body continues to move and attack and there is no more way to stop it.

**Comment by Filigrani** [comment]
Okay.
1.
`To play multiplayer, we had to activate the "public host" and "steam peer to peer"` You not have to enable public server, if you leave it disabled, you still able to invite by stean invites, just keep Steam P2P enabled. About none steam connection(hamachi, radmin, direct ip connection) problems is not problem of the mod, but connection peoblems, is what I can't fix, so can do with this anything.
2.
`The gender of the characters are not maintained. Each time we start the session with my friend, we discover ourselves as men and then women the next day.`
That known and will be fixed.
3.
`Sometimes my friend sees things and objects that I don't, and vice versa.`
What objects exacly? Breakable objects? Or tree limbs and stones? Tree limbs and stones belong to radial spawn objects that completly random for every played I am never told it synced or will be synced.
4.
`The objects that my friend puts down, I don't see them and vice versa.`
No one told you it synced, it never was.
5.
`Likewise, when we make a fire, my friend does not see it and vice versa.`
No one told you it synced, it never was.

**Comment by davi919** [comment]
about immortal animals, did it just happen to me, or is there an explanation for that too?

**Comment by NicksQ69** [comment]
There are certain objects such as firearms (rifle) where one does not perceive while the other does.

**Comment by Filigrani** [comment]
All listed things here fixed in now days builds of the mods.
