### ISSUE TITLE
Top right button doesn't direct to Multiplayer/settings/customization

### ISSUE THREAD

**Issue by Sigvaldas** [Filigrani/SkyCoop#50]
**Mod Version:** v11.1  
**Game Version:** v2.01
**Launcher:** Steam
**Additional mods installed:** No
**Perspective:** not sure it is main menu

### Description
After getting flairs button which is located in top right corner in the menu which should point to Multiplayer/settings/customization doesn't work.

### How to reproduce
1. You will get flair from dev of the game. For example pie from pie event
2. After you get that flair you turn on the game
3. In main menu top right corner you see button that you got new flair
4. you click it
5. then click confirm(or something similar)

### Expected behavior
I expect to be pointed into Multiplayer/settings/customization screen

### Logs

**Host side log**
```
added attachemnt
```
[MelonLoader_23-01-17_13-16-09.458.log](https://github.com/Filigrani/SkyCoop/files/10434678/MelonLoader_23-01-17_13-16-09.458.log)

**Comment by Filigrani** [comment]
Fixed in 11.2
