### ISSUE TITLE
Crash game, version game 2.0.2.

### ISSUE THREAD

**Issue by drfrxx** [Filigrani/SkyCoop#51]
**Mod Version:** v0.11.1 
**Game Version:** v2.0.2  
**Launcher:** Steam
**Additional mods installed:** No
**Perspective:** Host

### Description
Explain the issue you're experiencing.

### How to reproduce
1. Being host/client.
2. On region '....'
3. Do  '....'
3. It works wrong / it wasn't working.

### Expected behavior
If not obvious, what did you expect to happen?

### Logs

**Host side log**
```
Paste crash between the triple backticks.

Log can be found in game directory "TheLongDark\MelonLoader\Logs", please make sure that you paste CORRECT LOG, every log named with date of session, so please paste log only from session where you exactly had a problem.

If you are the client of a session, please ask your friend host to send you a log file. (Even if only client(s) experienced the problem, a host log is required in any way).
```
**Client side log**
[MelonLoader_23-01-24_00-30-00.850.log](https://github.com/Filigrani/SkyCoop/files/10483795/MelonLoader_23-01-24_00-30-00.850.log)

```
Paste crash between the triple backticks.

Log can be found in game directory "TheLongDark\MelonLoader\Logs", please make sure that you paste CORRECT LOG, every log named with date of session, so please paste log only from session where you exactly had a problem.

If you are the host of the session, please ask your friend(s) client(s) that experienced a problem, to send their logs to you.
```
даже не знаю как объяснить, но игра просто крашится при попытке загрузить её. как без мода, так и с ним.
в логах всё должно написано.

**Comment by tilkinsc** [comment]
What needs to be done to make this work with current version?

**Comment by tilkinsc** [comment]
I took a look into the code. It appears the developer has hung on to obsolete code for too long and a lot of missing references due to the game updating. The code is a complete mess and investment cost is too much especially without proper build instructions.

**Comment by Filigrani** [comment]
Delete, "Mods", "Plugins", and "Melonloader" folders and perform another installation with using Sky Co-op Installer.

**Comment by tilkinsc** [comment]
This is the current state of running Melonloader with the current version of the game. It is reproducible.

**Comment by Filigrani** [comment]
> 

They stated they are using game version 2.02, not a current game version release.

**Comment by Filigrani** [comment]
[00:30:01.942] Game Version: 2.02
[00:30:00.854] MelonLoader v0.5.7 Open-Beta

This is what has been provided in the logs of the current issue. We not talking about current version release, because problem is obvious. They are trying to run mod build 11.1 that has been made for 2.02, and not for 2.06+.

**Comment by tilkinsc** [comment]
Ah okay. Versioning is fun. What needs to be done to make this mod able to run 2.06+?

**Comment by Filigrani** [comment]
> Ah okay. Versioning is fun. What needs to be done to make this mod able to run 2.06+?

Common, don't be silly, you exactly know that game got DLC and now whole game rewriten with having it in mind, so most of already existen components become modular, or some function even missing, or moved to other menages. Also this now .net6 and there a lot of things that simply wont work. So please don't play a fool like this all is easy, you know exactly that its not.

**Comment by tilkinsc** [comment]
I think you are just cynical. I am very new to this game and was suggested this mod. As someone who only has epic I don't have a way to downgrade. I was looking to contribute. The fact that its .NET 6.0 I am rather familiar, but I don't appreciate how you treat people.
