### ISSUE TITLE
Can't use the save file from previous mod version

### ISSUE THREAD

**Issue by Grel00** [Filigrani/SkyCoop#52]
**Mod Version:** v11.0-11.2  
**Game Version:** v2.01   
**Launcher:** Steam 
**Additional mods installed:** No 
**Perspective:** Host 

### Description
Не получается загрузить сейв, начатый на версии мода до 11.0. При попытке загрузить игру выдается ошибка как в issue #37 
![image](https://user-images.githubusercontent.com/123811414/215265196-fefcd2e6-0a7d-49ef-a23a-c03666df42f3.png)
В логе от 06.01 сейв загружался, в логе от 15.01 и 28.01 уже нет

### Logs

**Host side log**
`
[MelonLoader_23-01-28_14-33-25.632.log](https://github.com/Filigrani/SkyCoop/files/10527199/MelonLoader_23-01-28_14-33-25.632.log)
``
[MelonLoader_23-01-06_20-21-08.886.log](https://github.com/Filigrani/SkyCoop/files/10527170/MelonLoader_23-01-06_20-21-08.886.log)
[MelonLoader_23-01-15_18-13-30.901.log](https://github.com/Filigrani/SkyCoop/files/10527171/MelonLoader_23-01-15_18-13-30.901.log)
[MelonLoader_23-01-28_14-33-25.632.log](https://github.com/Filigrani/SkyCoop/files/10527172/MelonLoader_23-01-28_14-33-25.632.log)
```

**Comment by Filigrani** [comment]
You can't use saves from 11.1 on 11.2. This works as intended. Save algorithm has been changed for improvements of performance and expanding functionality

**Comment by Grel00** [comment]
Saves from version 10.4 can't be used on version 11.0 either? This issue started from version 11.0
