### ISSUE TITLE
Host button not work

### ISSUE THREAD

**Issue by WaveBulgaria** [Filigrani/SkyCoop#6]
When I click the host button nothing happens and when I click twice it brings me back to the game

**Comment by JaGuaRjeN** [comment]
Same thing happens to me.  Sometimes it will randomly work.

**Comment by Filigrani** [comment]
Update to last version of the mod. If you click one. Nothing visual should happen only log message about server is up at the console. In last version of the mod host button become inactive if you already hosting. So is not possible to press it twice on last version of the mod.
