### ISSUE TITLE
Problem with voice chat

### ISSUE THREAD

**Issue by CainDream** [Filigrani/SkyCoop#65]
**Mod Version:** v0.11.16
**Game Version:** v2.01 "Perilous Constraint"   
**Launcher:** Steam  
**Additional mods installed:** No
**Perspective:** Both

### Description
Скачали с другом через установщик мод на стимовскую v2.01 "Perilous Constraint". В игре столкнулись с некорректно работающим голосовым чатом: слышно голос компаньона только в одном наушнике, несмотря на местоположение персонажа в пространстве. С рацией то же самое - звук только в одном наушнике. При этом сам игровой мир прослушивается отлично: шаги друг друга, шаги зверей и т.д.

### How to reproduce
1. Being host/client. - у всех.
2. On region '....' - в любом.
3. Do  '....' - неважно.

### Expected behavior
If not obvious, what did you expect to happen?
Ожидали нормального распространения звука.

### Logs
**Host side log**
```
[MelonLoader_23-06-16_21-54-48.402.log](https://github.com/Filigrani/SkyCoop/files/11773331/MelonLoader_23-06-16_21-54-48.402.log) - здесь мы просто стояли в администрации турбазы и болтали в голосовой чат, создавая лог.
```

**Client side log**
```
[MelonLoader_23-06-16_21-54-24.617.log](https://github.com/Filigrani/SkyCoop/files/11773255/MelonLoader_23-06-16_21-54-24.617.log) - здесь мы просто стояли в администрации турбазы и болтали в голосовой чат, создавая лог.
```

**Comment by Filigrani** [comment]
Пока не смог во создать проблему. Нет ли каких либо утилит для объёмого звука типа эмуляторов 5.1 или 7.1 звука?

**Comment by Filigrani** [comment]
Не смог воспроизвести проблему.
