### ISSUE TITLE
will 2.17 be supported?

### ISSUE THREAD

**Issue by o0Julia0o** [Filigrani/SkyCoop#67]
**Mod Version:** v11.9 Pre 
**Game Version:** v2.17   
**Launcher:** Steam
**Additional mods installed:** No
**Perspective:**Both

### Description
The installer shows, that the game-version is not supported - i have to use on my own risk.

### How to reproduce
1. Being host/client.
2. On region '....'
3. Do  '....'
3. It works wrong / it wasn't working.

### Expected behavior
I installed the version 11.0 Pre on 2.17 with the SkyCoopInstaller. Will it work or do i have to downgrade my game-version? Or will 2.17 be supported in a few month?

**Comment by Filigrani** [comment]
No, it will not work. Mod only works with 2.01-2.02 version of the game

**Comment by o0Julia0o** [comment]
Thank you. So 2.02 is the last version which will be ever supported by the SkyCoop-Mod?

**Comment by Filigrani** [comment]
Future is a mystery, past is a history, present is a gift, that why it called a present.
