### ISSUE TITLE
What's wrong with a new version of Scy Coop? On my friend's pc it's working without issues, but on my pc there is an error.

### ISSUE THREAD

**Issue by Ignatyev01** [Filigrani/SkyCoop#71]
A newer version of the installer is available, please download the latest version. (If you have already downloaded the latest version and you see this message, it means that the installer does not have Internet access.)

How can i fix it
(My internet is working)

**Comment by Ignatyev01** [comment]
![114](https://github.com/Filigrani/SkyCoop/assets/62886243/907f4206-31e4-433b-86f8-5d8c0db58f78)

**Comment by Filigrani** [comment]
This is repository of the mod.

**Comment by Filigrani** [comment]
Here is repo of the intaller: https://github.com/RED1cat/SkyCoopInstaller/issues
